# Generated by Django 5.0.3 on 2024-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_room', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('computers', models.IntegerField(blank=True, null=True)),
                ('board', models.CharField(choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=1)),
            ],
        ),
    ]
