# Generated by Django 5.0.3 on 2024-03-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_bloco', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='bloco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='room_bloco', to='rooms.bloco'),
            preserve_default=False,
        ),
    ]
